[project]
name = 'Task-Pay'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.Task-Allocation]
path = 'contracts/Task-Allocation.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
